name: Dev

on:
  push:
    branches:
      - master

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.Docker_Username }}  
          password: ${{secrets.DockerPassword}}

       
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/server:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/server:latest
     
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker stop server || true
            docker rm server || true
            docker rmi ${{ secrets.DOCKER_USERNAME }}/server:latest || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/server:latest
            docker run -p 8080:8080 -d --rm --name server ${{ secrets.DOCKER_USERNAME }}/server:latest